import os
import pathlib

dirname = os.path.dirname(os.path.abspath(__file__))
rootFolders = [dirname + "/rte",
           dirname + "/ThanOS"]
targetFile = dirname + "/ThanOS/src/common/ObjectInfo.java"
packages = ["java.lang",
            "rte",
            "collections",
            "devices",
            "io",
            "kernel",
            "kernel.memory",
            "kernel.scheduler",
            "shell",
            "util"]

print("Path: " + dirname)

def main():
    f = open(targetFile, "w")
    f.write("package common;\n\n")

    for p in packages:
        f.write("import " + p + ".*;\n")

    f.write("\n/** Generated by UpdateObjectInfo.py **/")
    f.write("\npublic class ObjectInfo\n")
    f.write("{\n")
    f.write("\tpublic static String getName(Object o)\n")
    f.write("\t{\n")
    f.write("\t\tif (o == null)\n")
    f.write("\t\t\treturn \"null\";\n")

    for r in rootFolders:
        for path, file in getFiles(r):
            if file != "Object.java":
                f.write("\t\tif (o instanceof " + file[:-5] + ")\n")
                f.write("\t\t\treturn \"" + file[:-5] + "\";\n")

    f.write("\t\tif (o instanceof Object)\n")
    f.write("\t\t\treturn \"Object\";\n")

    f.write("\t\treturn \"Unknown\";\n")
    f.write("\t}\n")
    f.write("}\n")
    f.close()


def getFiles(root):
    for path, dirs, files in os.walk(root):
        yield from ((path, file) for file in files if pathlib.Path(file).suffix == '.java')


main()
